name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Check format
        run: cargo fmt --check
      - name: Build
        run: cargo build --release
      - name: Test
        run: cargo test --release -- --nocapture
      - name: Publish
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --no-verify
      - name: Merge Dependabot PR
        if: github.actor == 'dependabot[bot]' && github.event.pull_request
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr merge ${{ github.event.pull_request.number }} --auto --merge
